### PR TITLE
Add Node.js program to scan for reflashed LYWSD03MMC

### PR DESCRIPTION
**Pull request by haraldkubota**
It took me some tries to find the reflashed LYWSD03MMC, so I wrote a short Node.js program to find them and print out the advertised data (temperature, humidity and battery).
It be used to simply confirm advertisements are send out, what the device names are, and whether your Bluetooth works. Turns out the latter initially did not until I used a Bluetooth 4 USB dongle.

### CODE REVIEW

**Comment by haraldkubota** [comment]
Hmm...not much I can do here as the integration is...broken I guess:

/usr/bin/docker exec  c4d0ac1b3b8ea06d3f1ac29b68e37e50cd685d83de06c7f7c8a39dc23df0fe03 sh -c "cat /etc/*release | grep ^ID"
Error: Resource not accessible by integration

**Comment by atc1441** [comment]
Hey. Should i merge the pr?
Or is the error a problem for it ?

**Comment by haraldkubota** [comment]
Hi, the automatic build fails. I doubt it's a problem I introduced with my PR, so yes, please merge if you think this is useful.
Not everyone uses Node.js, but those who do will (I hope) appreciate a simple program to find the reflashed thermometers. I certainly use it a lot. And I guess some other people might benefit from it too.
And maybe it's a start of more similar contributions.

**Comment by atc1441** [comment]
There we go :) 

Thank you for your contribution

**Pull request merged**
