### PR TITLE
Added a way towards easy builds

### PR DESCRIPTION
**Pull request by rvben**
Hello!

I believe that it's very important, for the success of a project (and forgetting contributions), that compilation is as easy as possible, 
to make it as painless as possible. With Docker, there's no worry about having the right SDK's or having the code folder in the right location, it just works.

I've added the Dockerfile and a simple Makefile to show how easy it can be. If you want, I can make a separate repository for this 'builder', but I think it's easier to maintain if the compilation environment is kept close to the code.

Let me know what you think :)

Have a great day!

Ruben

### CODE REVIEW

**Comment by rvben** [comment]
Noticed that there's already a Docker image that is used for CI, so adjusted the Makefile to use that one instead of my own Dockerfile. :) Added a PR for that Docker image in the respective repository with some improvements.

**Comment by atc1441** [comment]
Hey thank you for the PR
Unfortunately i did not work with docker till now since i am mostly using windows for my projects.

Does this PR changes some other files or only adds the Dockerfile and Makefile in root on the repo ?

**Comment by benleb** [comment]
This just adds another make target (`build`) to the Makefile which starts a docker container to build the firmware image 👍

**Review by benleb — APPROVED** [review]
Looks good 👍

**Comment by atc1441** [comment]
Perfect :)

**Pull request merged**
