### PR TITLE
Trying again!

### PR DESCRIPTION
**Pull request by cricri-pingouin**
I closed my previous pull request. I have no idea what I did wrong to create conflicts.
Following your reply, I try to make the battery level section clearer.

### CODE REVIEW

**Comment by atc1441** [comment]
Thank you again, worked as you can see :)

**Comment by cricri-pingouin** [comment]
Yipee! No idea how I managed to mess up the first time around. I just closed the request and tried again after doing more changes! Hope you are happy with my changes by the way, it was mostly:
- In OTA, mentioned the stock firmware is linked in a section at the bottom of the readme.
- In custom firmware, mentioned the guide is in Chinese and added a google translate link to English.
- Reformulated the battery display section.

**Comment by atc1441** [comment]
Yes i really like such help :)
As i am not a native english writer most errors come unknowlingly or just stupid mistakes because it was to late.

**Comment by cricri-pingouin** [comment]
That's fine, I'm not a native English speaker either. But then, I've been living in the UK for more than 20 years! Which also means I don't live in the EU anymore.
Anyway, I'd rather help this way because I wouldn't be able to help you with code.

**Pull request merged**
